stroka = input()
a = stroka.count('а')
z = stroka.count('я')
s = stroka.count('ы')
e = stroka.count('у')
t = stroka.count('е')
j = stroka.count('о')
m = stroka.count('ю')
b = stroka.count('и')
r = stroka.count('э')
y = stroka.count('ё')
print(a + z + s + e + t + j + m + b + r + y)